use std::fmt;
use std::ops::Deref;
use std::rc::Rc;

use ash::khr;
use ash::prelude::VkResult;
use ash::vk;

use super::{CommandPool, Instance, PhysicalDevice, Pipeline, Queue, Swapchain};

/// Cheap handle to a `VkDevice`: cloning bumps a refcount, and the device is
/// destroyed once the last clone — including the ones held by every object it
/// created — is gone.
///
/// Derefs to [`ash::Device`], so every `ash` entry point is available; the
/// inherent methods (here and the ones generated by `device_object!`) shadow the
/// ones that should hand back a wrapper.
#[derive(Clone)]
pub struct Device(Rc<DeviceInner>);

struct DeviceInner {
    raw: ash::Device,
    /// Keeps the physical device, and through it the instance, alive: the
    /// device has to be destroyed before `vkDestroyInstance`.
    physical_device: PhysicalDevice,
}

impl Device {
    /// # Safety
    /// - `raw` must have been created from `physical_device`;
    /// - this takes ownership of `raw`: nothing else may destroy it.
    #[inline]
    pub unsafe fn from_raw(physical_device: PhysicalDevice, raw: ash::Device) -> Self {
        Self(Rc::new(DeviceInner {
            raw,
            physical_device,
        }))
    }

    #[inline]
    pub fn physical_device(&self) -> &PhysicalDevice {
        &self.0.physical_device
    }

    #[inline]
    pub fn instance(&self) -> &Instance {
        self.0.physical_device.instance()
    }

    /// Looks up a queue the device already owns — nothing is created here, so
    /// there is nothing to destroy either.
    ///
    /// # Safety
    /// `queue_family_index` must be one of those asked for in the
    /// `VkDeviceCreateInfo`, and `queue_index` below the count requested for it.
    #[inline]
    pub unsafe fn queue(&self, queue_family_index: u32, queue_index: u32) -> Queue {
        let raw = unsafe { self.0.raw.get_device_queue(queue_family_index, queue_index) };
        unsafe { Queue::from_raw(self.clone(), raw, queue_family_index) }
    }

    /// # Safety
    /// Same contract as `vkCreateCommandPool`.
    pub unsafe fn create_command_pool(
        &self,
        create_info: &vk::CommandPoolCreateInfo,
    ) -> VkResult<CommandPool> {
        let raw = unsafe { self.0.raw.create_command_pool(create_info, None) }?;
        Ok(unsafe { CommandPool::from_raw(self.clone(), raw) })
    }

    /// Loads `VK_KHR_swapchain` for this swapchain and creates it. The loader
    /// lives in the returned [`Swapchain`], which is what lets it destroy
    /// itself; recreating on resize pays for one more loader, which is a handful
    /// of `vkGetDeviceProcAddr` calls.
    ///
    /// # Safety
    /// - `VK_KHR_swapchain` must be enabled on this device;
    /// - same contract as `vkCreateSwapchainKHR` otherwise.
    pub unsafe fn create_swapchain(
        &self,
        create_info: &vk::SwapchainCreateInfoKHR,
    ) -> VkResult<Swapchain> {
        let loader = khr::swapchain::Device::new(self.instance(), self);
        let raw = unsafe { loader.create_swapchain(create_info, None) }?;
        Ok(unsafe { Swapchain::from_raw(self.clone(), loader, raw) })
    }

    /// # Safety
    /// Same contract as `vkCreateGraphicsPipelines`.
    ///
    /// On partial failure `ash` still hands back the pipelines it managed to
    /// create; they come back wrapped, so dropping the `Err` cleans them up.
    pub unsafe fn create_graphics_pipelines(
        &self,
        cache: vk::PipelineCache,
        create_infos: &[vk::GraphicsPipelineCreateInfo],
    ) -> Result<Vec<Pipeline>, (Vec<Pipeline>, vk::Result)> {
        let wrap = |raws: Vec<vk::Pipeline>| {
            raws.into_iter()
                .filter(|raw| *raw != vk::Pipeline::null())
                .map(|raw| unsafe { Pipeline::from_raw(self.clone(), raw) })
                .collect()
        };

        match unsafe {
            self.0
                .raw
                .create_graphics_pipelines(cache, create_infos, None)
        } {
            Ok(raws) => Ok(wrap(raws)),
            Err((raws, result)) => Err((wrap(raws), result)),
        }
    }
}

impl Deref for Device {
    type Target = ash::Device;

    #[inline]
    fn deref(&self) -> &Self::Target {
        &self.0.raw
    }
}

impl fmt::Debug for Device {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Device").field(&self.0.raw.handle()).finish()
    }
}

/// Handle identity: two `Device` values are equal when they refer to the same
/// `VkDevice`.
impl PartialEq for Device {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        Rc::ptr_eq(&self.0, &other.0)
    }
}

impl Eq for Device {}

impl Drop for DeviceInner {
    fn drop(&mut self) {
        unsafe { self.raw.destroy_device(None) };
    }
}
